
name: CI

on:
   push:
    branches:
    - main
   pull_request:
    branches:
    - main
  
jobs:
  build:
      runs-on: ubuntu-latest
      permissions:
         contents: write
         pages: write
      
      steps:
         - uses: actions/checkout@v2.4.0  
         - name: Set up Python 3.13
           uses: actions/setup-python@v2.4.0  
           with:
               python-version: "3.13"
           
         - name: Install dependensies
           run: |
              python -m pip install --upgrade pip
              pip install pipenv
              pipenv install --system
              playwright install chromium
              
         - name: Run tests
           run: pytest
           
         - name: Deploy 🚀
           if: always()
           uses: JamesIves/github-pages-deploy-action@4.1.5
           with:
             branch: gh-pages
             folder: reports
           env:
             GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
           
